Feature/anonymous voting
vocdoni/docs pull request #34
Opened 2021-07-07 15:24 UTC by arnaucube

[This PR depends on #32 being merged to `master` branch]

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/blind-signatures.md
> +> WIP
I would leave a more human readable message.

`This section is still a work in progress` 

Can we create an issue to have this written as well? Don't we have any documentation about it?

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +This document is splitted in two main sections:
```suggestion
This document is divided in two sections:
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- **Protocol design**: high level overview of the protocol, without giving much specific details, but showing the main idea.
```suggestion
- **Protocol design**: high level overview of the protocol.
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- **Implementation spec**: step by step specification, explaining all the details, the data structures used, how things are hashed, etc. With the aim to avoid leaving any ambiguous concept.
```suggestion
- **Implementation spec**: detailed specification, featuring the relevant data structures, how things are hashed, etc.
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The census proof (also called franchise proof) enables user privacy and allows anonymous voting.
The `census proof` also applies to signed votes, doesn't it?

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The starting point is a [Merkle Proof](/architecture/census-overview?id=the-census), which efficiently proves that a public key belongs to a Merkle Tree (census). However, using this proof alone woul
I think the link is now `architecture/census-overview.html`

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> ++ The same circuit can be used for any `process` with the same census (max) size
```suggestion
+ The same circuit can be used for any `process` with a census size of the same range (10k, 100k, 1M, etc).
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +    - User's *voting key* (censustree leaf key): `leafKey = poseidon(pk.x, pk.y)`
```suggestion
    - User's *voting key* (censustree leaf key): `leafKey = poseidon([pk.x, pk.y])`
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +    - Where each leaf contains each hash of user's `pk` (*voting key*)
```suggestion
    - Where each leaf contains the hash of each user's `pk` (*voting key*)
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +![](https://i.imgur.com/RVnFDqP.png)
Wouldn't it make sense to upload this file here?

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *censusRoot*: computed by the *CensusAuthorithy* from the *Census Tree*
Who is the `CensusAuthorithy`? Maybe we can explain this a bit better? (two step process, this is the second Merkle Tree, etc) ?

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *censusSiblings*: computed by the *CensusAuthorithy*, it's the *Merkle Proof*
Comment that the proof is retrieved from the Vochain? What kind of Merkle Tree is it (arbo)? etc

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *voteValue*: value of the *User* vote
How do we serialize/compute it? The origin is a JSON payload

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +    - `relayerProof = poseidon.Hash(nullifier, relayerPublicKey)`
Are we considering ZK rollups and relayers at this point?

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *revealKey*: not known by the user at the proof generation moment
Is there a particular order in which they should appear? When there is no reveal key published, should the input still be `["0"]` and not `["0", "0", ... ]` ?

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The client & Vochain need a way to unequivocally identify those circuits, in order to user the proper `Proving key`, `Witness calculator` and `Verification key` for each circuit.
```suggestion
Both the client and the Vochain need a way to univocally identify those circuits, in order to user the proper `Proving key`, `Witness calculator` and `Verification key` for each circuit.
```

2021-07-12 09:44 UTC, brickpop commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The following defines the way how the circuits are identified in the client and also inside the Vochain through a Protobuf enum type. Each `ProofZkSNARK` protobuf packet will have a `Type` identifier
```suggestion
Circuits are identified across the stack by using a Protobuf enum type. Each `ProofZkSNARK` protobuf package will have a `Type` identifier indicating which circuit the proof belongs to, so the Vochain knows which `Verification Key` to use for verifying the proof.
```

2021-07-12 13:18 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +![](https://i.imgur.com/RVnFDqP.png)
Agree, for the moment was a hackmd generated link as this content was copy&pasted here directly from hackmd each time that the hackmd was updated.
Added the original image (which contains the draw.io editable data source) & updated the link to it.

2021-07-12 13:20 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *censusSiblings*: computed by the *CensusAuthorithy*, it's the *Merkle Proof*
Added a line regarding the Vochain origin of the siblings data. The MerkleTree type is defined in the `Merkle Tree` section

2021-07-12 13:21 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *voteValue*: value of the *User* vote
This would need to be discussed. For the moment in the circuit related code, it's assumed that the `voteValue` is a biginteger.

2021-07-12 13:24 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- *revealKey*: not known by the user at the proof generation moment
The length of the arrays `relayerProof` & `commitKey` are determined by the circuit parameter `nMiners`.
(Adding this description to the doc)

2021-07-12 13:26 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The starting point is a [Merkle Proof](/architecture/census-overview?id=the-census), which efficiently proves that a public key belongs to a Merkle Tree (census). However, using this proof alone woul
Updated

2021-07-13 09:31 UTC, arnaucube commented
Update: added a commit to update the spec to the last changes discussed this morning: https://github.com/vocdoni/docs/pull/34/commits/10df391bc7c8fea2cdc58be2941d815d92dd2f05

2021-07-13 19:46 UTC, NateWilliams2 requested changes
I made some edits for clarity and left a few comments :)

2021-07-13 19:46 UTC, NateWilliams2 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> ++ It relies on a **trusted setup ceremony**
Could you link to somewhere to read about what a trusted setup is?

2021-07-13 19:46 UTC, NateWilliams2 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The MerkleTree needs to be a zkSNARK-friendly implementation. As currently we are using [Circom]() for the zkSNARK circuits, we need to be compatible with the [circomlib](https://github.com/iden3/cir
`[Circom]()` needs a link destination

2021-07-13 19:46 UTC, NateWilliams2 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +![](./circuit-with-keykeepers-keys-diagram.png)
what software did you use to generate this diagram? Could it be fetched directly from the source so that the designs are also editable by anyone? 
For example, many of the diagrams are created with draw.io and hosted on the https://github.com/vocdoni/design/tree/main/docs repo so they can be edited without re-downloading

2021-07-13 19:46 UTC, NateWilliams2 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +        - The design of the *MerkleTree* used in circomlib provokes different lengths in the siblings returned when generating a *MerkleProof*
I'm confused what this line means.

2021-07-14 07:07 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +![](./circuit-with-keykeepers-keys-diagram.png)
Yes, it's done with draw.io, and when saving the image marked the checkbox to include the editable data inside the png for future editions.
Didn't knew about a separated repository for the diagrams. Maybe these kind of diagrams are dependent on what the `docs` repo has as content and would be more useful with the images in the same repo & dir than the `.md` file? (including the images that are editable from drawio, like this one)
For example, this current image, it can live here in this directory, and if there is one change in the design of the protocol we just need to add 1 commit in this repo updating the `md` files and the drawio image. While if we need to update the `md` of this repo and then the image of the `design` repo, would be 2 commits in two different repos, with the dependency that for example the PR in the `design` repo with the new image passes, but in the `docs` repo maybe somebody does a comment with a suggestion of change of the spec, so the `docs` PR needs to be updated, but the `design` repo PR is already merged. This could be avoided by adding some kind of 'human protocol' where if somebody creates a new PR that depends on another PR of another repo there should be some kind of coordination, but in the case of these images, maybe it's easier & faster to just have the images in the same directory where it is the document which contains the image.
But maybe I'm missing some reason behind to have the images in a separated repo, so I can move this image into that repo if needed.

2021-07-14 07:08 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +The MerkleTree needs to be a zkSNARK-friendly implementation. As currently we are using [Circom]() for the zkSNARK circuits, we need to be compatible with the [circomlib](https://github.com/iden3/cir
Right! Updated

2021-07-14 07:12 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> ++ It relies on a **trusted setup ceremony**
Right! Added a link to an article

2021-07-14 07:17 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +        - The design of the *MerkleTree* used in circomlib provokes different lengths in the siblings returned when generating a *MerkleProof*
Added a bit of more explanation and a link to the spec of the merkletree

2021-07-14 16:55 UTC, NateWilliams2 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +![](./circuit-with-keykeepers-keys-diagram.png)
yes, you're right. I'll work on moving all the designs into this repo. Is the source for this design in this repo?

2021-07-14 16:56 UTC, NateWilliams2 approved these changes

2021-07-14 17:35 UTC, merged

2021-07-14 18:27 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +![](./circuit-with-keykeepers-keys-diagram.png)
Yes, the diagram source is embedded in the png image itself.