Add process flag preRegister &update zk-census doc
vocdoni/docs pull request #56
Opened 2021-07-19 16:14 UTC by arnaucube

- Add process flag preRegister
    - Update anonymous-voting/zk-census-proof doc replacing
    `CensusRegisterFunction` by `CensusOrigin`

2021-07-19 16:45 UTC, NateWilliams2 approved these changes
Made some minor edits, including adding `preRegister` to the gateway api example for processes. looks good to me.

2021-07-20 12:13 UTC, p4u commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- CSV with pre-register: `preRegister=true`, `CensusOrigin=OFF_CHAIN_TREE`
I'd not say here just CSV, its hard to understand. 

`Census Merkle Tree (from CSV file or private database) with pre-register:`

2021-07-20 12:18 UTC, p4u commented on src/architecture/smart-contracts/process.md
> +- `false` ⇒ The `CensusRoot` will be defined through a phase where the users need to register, using the `CensusRegisterProof` depending on the `CensusOrigin` of the process.
false: There is not registration phase thus the census root used for validate votes is the censusRoot parameter defined by the newProcessTx transaction

true: There is a registration phase, the census root parameter defined by newProcessTx is used only during the registration (before the process startBlock is reached). The voting censusRoot will be built inside the Vochain when registerVoterKeyTx are send by the elegible voters

2021-07-20 13:52 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- CSV with pre-register: `preRegister=true`, `CensusOrigin=OFF_CHAIN_TREE`
:+1:  Added

2021-07-20 13:53 UTC, arnaucube commented on src/architecture/smart-contracts/process.md
> +- `false` ⇒ The `CensusRoot` will be defined through a phase where the users need to register, using the `CensusRegisterProof` depending on the `CensusOrigin` of the process.
:+1:  Added

2021-07-20 15:13 UTC, ed255 requested changes

2021-07-20 15:13 UTC, ed255 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +  Organizer->>Vochain: 1. create new voting process (newProcessTx) & define the CensusOrigin=CSVCensus
`CSVCensus` is not a valid CensusOrigin.  Maybe use `OFF_CHAIN_TREE` or `OFF_CHAIN_TREE_WEIGHTED`

2021-07-20 15:13 UTC, ed255 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- 1. *[O+V]* Create **new voting process** (newProcessTx) & define the CensusOrigin=CSVCensus
Same as before

2021-07-20 15:13 UTC, ed255 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +    - **CensusOrigin** determines the checks:
The next line mentions `Ethereum Root`, but maybe you're refering to the `Census Root`?

2021-07-20 15:13 UTC, ed255 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +  Organizer->>Vochain: 1.0. create new voting process (newProcessTx) & define the CensusOrigin=EthStorageProofsCensus
```suggestion
  Organizer->>Vochain: 1.0. create new voting process (newProcessTx) & define the CensusOrigin=ERC20
```

Following spec at https://github.com/vocdoni/dvote-protobuf/blob/4f28acf85d4607bc70213f9a04fdb1acaac42870/src/vochain/vochain.proto#L261

2021-07-20 15:13 UTC, ed255 commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +- 1. *[O+V]* Create **new voting process** (newProcessTx) & define the CensusOrigin=EthStorageProofsCensus
```suggestion
- 1. *[O+V]* Create **new voting process** (newProcessTx) & define the CensusOrigin=ERC20
```

2021-07-20 15:18 UTC, arnaucube commented on src/architecture/protocol/anonymous-voting/zk-census-proof.md
> +    - **CensusOrigin** determines the checks:
No, here it's referring to the *Ethereum Root*, as the *Vochain* will need to check the *MerkleProof* (*EthStorageProof*) with the defined *Ethereum Root*.

2021-07-20 15:34 UTC, ed255 approved these changes

2021-07-20 16:30 UTC, merged