Protocol layer clarification
vocdoni/docs pull request #58
Opened 2021-07-19 19:16 UTC by NateWilliams2

2021-08-02 15:29 UTC, ed255 requested changes

2021-08-02 15:29 UTC, ed255 commented on src/integration/census/general.md
> ++ [off-chain registry database](registry.md).
The previous line already refers to `regystry.md`.

2021-08-02 15:34 UTC, p4u reviewed
Regarding the census, I think we should split it on two main sections:

- Off chain based census (merkle tree)
- On chain based census (ethereum erc20)

Here some details that might be reused: https://www.notion.so/aragonorg/Introducing-Vocdoni-Bridge-cf7e73d38c4a45788358e9a1497cdf19

2021-08-02 15:35 UTC, ed255 commented
I see that these three files are being deleted:
- `src/manager/manager-api.md`
- `src/manager/overview.md`
- `src/manager/push-notifications-api.md`
- `src/manager/registry-api.md`
These files contain explanations about the funcionality of the manager and the details of its API.  Could you briefly explain why are these files being deleted, so that I can understand this change in context?  Thanks!

In `src/architecture/services/census-service.md` now there's a warning saying that the section is being deprecated.  But I understand we still use a census service in our product.  Why is this section being deprecated?  Will it be removed completely?  Or moved to some place else?  Thanks!

2021-08-02 15:37 UTC, p4u commented
The Manager does not exist anymore (its deprecated). We want to rescue it it some moment but we prefer to have in the current documentation only those things which are currently working.

2021-08-02 15:45 UTC, NateWilliams2 commented
@ed255 I was under the impression that the census service was no longer used, and that the current frontend does all the census operations itself. Is this wrong? cc @p4u

2021-08-02 15:59 UTC, p4u commented
Ah wow, I did not saw that. Yes the census service is being used, it's part of the Gateway. I was talking about the registry API (which is actually deprecated for now).

2021-08-02 16:08 UTC, NateWilliams2 commented
@p4u I see. So, after generating the Merkle tree from the CSV, the census service is used to publish the tree and generate the proofs themselves?

2021-08-02 16:10 UTC, p4u commented
The CSV Merkle Tree is generated using the census-service of the gateways. The CSV only changes the origin of the information, it can be either a private database (as it was before with the Manager) or a CSV file provided directly by the user.

2021-08-02 16:13 UTC, ed255 approved these changes

2021-08-04 08:55 UTC, p4u commented
@brickpop was also working on the kind of census descriptions, in separated document. Maybe he could share the link and also review the census section.

2021-08-04 22:20 UTC, NateWilliams2 commented
plz review again if possible @p4u  :)

2021-08-05 09:46 UTC, p4u commented on src/integration/census/csv.md
> +This information is normalized, concatenated, and then hashed to create a public key for each user. The public keys are added to the census Merkle Tree and then discarded, and only the Merkle Tree is
The information is also salted with the processId

2021-08-05 09:46 UTC, p4u approved these changes
LGTM, great work!

2021-08-05 17:00 UTC, merged