Move git branching guidelines inside docs repo
vocdoni/docs pull request #71
Opened 2021-09-08 21:34 UTC by NateWilliams2

This PR moves the git branching guidelines previously at https://github.com/vocdoni/protocol/wiki/Repository-branching-and-guideline into the documentation page.

It also adds the clarification "**The highest-number release-* branch is assumed to be active & deployed**"

2021-09-09 16:17 UTC, arnaucube approved these changes

2021-09-15 15:03 UTC, ed255 requested changes

2021-09-15 15:03 UTC, ed255 commented on src/about-us/repository-branching.md
> +Exception: before merging if the commit history is messy or dirty, squash them and add a big commit listing all modifications.
This is nearly identical to the contents at line 83

2021-09-15 15:03 UTC, ed255 commented on src/about-us/repository-branching.md
> ++ `git push origin <branch_name> --force`
This is the same as line 97

2021-12-14 16:05 UTC, merged